# Generated by Django 3.2.3 on 2021-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='auction',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='hide_price',
            field=models.BooleanField(blank=True),
        ),
    ]
