# Generated by Django 3.2.3 on 2021-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='type',
            field=models.CharField(choices=[('1', 'transcription'), ('2', 'academic writing'), ('3', 'article writing'), ('4', 'general'), ('5', 'tasks')], max_length=100),
        ),
    ]
