# Generated by Django 3.2.3 on 2021-07-15 12:09

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('2'), default_currency='USD', max_digits=14, null=True),
        ),
    ]
