# Generated by Django 3.2.3 on 2021-06-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='max_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
