# Generated by Django 3.2.3 on 2021-07-07 12:05

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='approved',
            field=partial_date.fields.PartialDateField(),
        ),
    ]
