# Generated by Django 3.2.3 on 2021-05-30 02:31

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AlterField(
            model_name='freelance',
            name='description',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='earned',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
