# Generated by Django 3.2.3 on 2021-06-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0002_alter_freelance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='on_escrow',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
