# Generated by Django 3.2.3 on 2021-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0002_auto_20210628_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='on_escrow',
            field=models.BooleanField(default=False),
        ),
    ]
