# Generated by Django 3.2.3 on 2021-07-08 21:24

from django.db import migrations, models
import flip.models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0002_alter_freelance_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=flip.models.name_file),
        ),
        migrations.AddField(
            model_name='freelance',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=flip.models.name_file),
        ),
    ]
