# Generated by Django 3.2.3 on 2021-05-25 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0003_alter_profile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'transcription'), ('2', 'academic writing'), ('3', 'article writing'), ('4', 'general'), ('5', 'tasks')], max_length=100)),
                ('company', models.CharField(choices=[('1', 'rev'), ('2', 'verbit'), ('3', 'transcribe me'), ('4', 'essay shark'), ('5', 'iwriters'), ('6', 'upwork')], max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('earned', models.IntegerField(default=0)),
                ('no_of_gigs', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=280)),
                ('price', models.IntegerField(default=0)),
                ('hide_price', models.BooleanField()),
                ('offers', models.BooleanField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('vpn_need', models.BooleanField()),
                ('verification_needed', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('original_email', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
