# Generated by Django 3.2.3 on 2021-07-08 22:36

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0003_auto_20210709_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14),
        ),
    ]
