# Generated by Django 3.2.3 on 2021-05-25 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0004_freelance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelance',
            name='age',
        ),
        migrations.AddField(
            model_name='freelance',
            name='date_of_reg',
            field=models.DateField(default=datetime.date(2021, 5, 25)),
            preserve_default=False,
        ),
    ]
