# Generated by Django 3.2.3 on 2021-07-08 23:19

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0004_alter_freelance_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='auction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='hide_price',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='offers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
    ]
