# Generated by Django 3.2.3 on 2021-05-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0004_auto_20210530_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='date_of_reg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
