# Generated by Django 3.2.3 on 2021-05-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0005_alter_socialmedia_date_of_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('1', 'accepted'), ('2', 'rejected'), ('3', 'waiting')], max_length=100),
        ),
    ]
