# Generated by Django 3.2.3 on 2021-07-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0005_alter_freelance_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='max_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
