# Generated by Django 3.2.3 on 2021-05-25 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip', '0005_auto_20210525_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='pub_date',
            field=models.DateField(default=datetime.date(2021, 5, 25)),
            preserve_default=False,
        ),
    ]
